### ISSUE TITLE
Storybook and expo-linear-gradient: Module not found error

### ISSUE THREAD

**Issue by DaveClissold** [Naturalclar/expo-typescript-starter#36]
Hi thanks for an awesome boiler plate. I am having a problem when i try to use the expo-linear-gradient package.  I get the following error
```
ERROR in ./node_modules/expo-linear-gradient/build/LinearGradient.js
Module not found: Error: Can't resolve './NativeLinearGradient' in '/local_location/node_modules/expo-linear-gradient/build'
```
Being new to development I'm not sure how to get past this, but I think it might ahve something to do with the file extensions for the NativeLinearGradient files are either .web.ts, .ios.ts or .android.ts.

Can you suggest any way of resolving this or where to begin looking for a fix?

**Comment by DaveClissold** [comment]
i have found out this is a bug in expo

**Comment by vannyy01** [comment]
How did you fix this?
